/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stdint.h"
#include "stdlib.h"

#include "stm32f103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"
#include "keypad.h"
#include "lcd.h"

unsigned int IRQ_Flag = 0;

void wait_ws(int x)
{
	unsigned int i,j ;
	for (i=0; i<x; i++)
		for (j=0; j<255; j++);
}

void EXTI9_CallBack(void)
{
	IRQ_Flag =1;
	LCD_WRITE_STRING("IRQ EXTI9 Is Happened _|-");
	wait_ws(1500);
}

int main(void)
{
	/* Enable Clock */
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();
	LCD_WRITE_STRING("Learn_IN_Depth...");
	LCD_clear_screen();
	LCD_WRITE_STRING("Eng.Taha Hamed");
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_CFG ;
	EXTI_CFG.EXTI_PIN = EXTI9PB9 ;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_Rising ;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_CallBack ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable ;

	MCAL_EXTI_GPIO_INIT(&EXTI_CFG);
	IRQ_Flag = 1 ;

	while(1)
	{
		if(IRQ_Flag)
		{
            LCD_WRITE_STRING("IRQ...");
            wait_ws(1000);
			LCD_clear_screen();
			IRQ_Flag =0;
		}
	}
}

